# Generated by Django 4.1.6 on 2023-02-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productpic', models.ImageField(null=True, upload_to='product_img')),
                ('productname', models.CharField(max_length=100)),
                ('productmodel', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=120, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
